"""initial schema: videos and events

Revision ID: 6b7840298971
Revises: 
Create Date: 2026-06-02 16:10:29.411394
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7840298971'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.String(length=128), nullable=False),
    sa.Column('worker_id_anonymized', sa.String(length=128), nullable=True),
    sa.Column('property_tag', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'anonymized', 'processed', 'failed', name='videostatus', native_enum=False, length=16), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(), nullable=True),
    sa.Column('anonymization_coverage', sa.Float(), nullable=True),
    sa.Column('anonymization_method', sa.String(length=64), nullable=True),
    sa.Column('anonymization_meta', sa.Text(), nullable=True),
    sa.Column('hand_pose_extracted', sa.Boolean(), nullable=False),
    sa.Column('hand_pose_extracted_at', sa.DateTime(), nullable=True),
    sa.Column('segmented', sa.Boolean(), nullable=False),
    sa.Column('segmented_at', sa.DateTime(), nullable=True),
    sa.Column('segmentation_cost_usd', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('property_tag', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_property_tag'), ['property_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_video_id'))
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_property_tag'))

    op.drop_table('events')
    op.drop_table('videos')
    # ### end Alembic commands ###
