"""add operator_height_cm and scene to videos

Revision ID: c2ef5f5dffdc
Revises: 6b7840298971
Create Date: 2026-06-03 19:26:58.460496
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ef5f5dffdc'
down_revision: Union[str, None] = '6b7840298971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator_height_cm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scene', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('scene')
        batch_op.drop_column('operator_height_cm')

    # ### end Alembic commands ###
